name: tf

on: 
  push:
    branches:
      - main
  pull_request:

jobs:
  terragrunt:
    name: tf
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      packages: read
      contents: read
      pull-requests: write
    env:
      tf_version: 1.9.4
      tg_version: 0.66.6    
      SNOWFLAKE_ACCOUNT: ${{ vars.SNOWFLAKE_ACCOUNT }}
      SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
      SNOWFLAKE_USER: ${{ vars.SNOWFLAKE_USER }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: "1.9.4"
          terraform_wrapper: false
        
      - name: Terraform Format
        id: fmt
        run: terraform fmt -check
        
      - name: setup Terragrunt
        uses: autero1/action-terragrunt@v3
        with:
          terragrunt-version: "0.66.6"
        
      - name: terragrunt init
        run: terragrunt init
        continue-on-error: true
        
      - name: terragrunt plan
        run: terragrunt plan
        continue-on-error: true
        
      - name: terragrunt apply
        run: terragrunt apply
        env:
          TF_CLI_ARGS: -auto-approve
